name: Check Build

on:
  schedule:
    - cron: '47 13 * * 3'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: 
          submodules: true
      - name: Checkout
        uses: actions/checkout@v5
        with: 
          repository: josephwright/ltx-talk
          path: ltx-talk
          submodules: true    
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           package_file: ./.github/tl_packages
      - name: Compile presentation
        env:
          TMPDIR: ${{ runner.temp }}      
        run: |
          cd ltx-talk
          l3build install
          cd $GITHUB_WORKSPACE
          file=./testing/$(basename -a -s .tex talktest.tex)  
          latexmk --pdf -pdflatex="pdflatex-dev %O %S" $file     
          mkdir art
          cp talktest.pdf art/
      - name: Upload build artifats
        uses: actions/upload-artifact@v4
        with:
          path: art
